### ISSUE TITLE
Emmet Inside of Inline Script Blocks

### ISSUE THREAD

**Issue by jrodl3r** [emmetio/emmet-atom#219]
Emmet is wreaking all sorts of havoc inside of inline script blocks within HTML files. It's adding HTML comments instead of the expects JS flavor, and also overriding other JS snippets as well (ex: instead of `"cl"+tab` producing the expected `console.log` Emmet generates an HTML tag `<cl></cl>`).

![bpohcuqsdb](https://cloud.githubusercontent.com/assets/869411/6375941/87e50566-bce8-11e4-84da-95fc31b3c0e2.gif)

Is there any way to disable Emmet inside of inline script tags? Or perhaps, are there any other know resolutions to this problem? 

I'm fully aware of #146 - However, it doesn't feel like this is just a matter or replacing or disabling `tab`, `cmd-/` or _any_ specific Emmet shortcuts. Isn't there a way for Emmet to detect it's not in HTML-land anymore, and has journeyed into an inline JavaScript tag?

I :heart: Emmet - Really hope there's a good soulution to this minor hiccup - Thx

**Comment by silvenon** [comment]
I was trying to hack on this, but I can't seem to figure out how to get the syntax of the current cursor position. I'll have to find how Atom did it for their snippets.

**Comment by jrodl3r** [comment]
I wonder if this project: [tvooo/scope-inspector](https://github.com/tvooo/scope-inspector) can help shed any light, and if scope would be narrow enough of an indicator to branch the logic?

**Comment by silvenon** [comment]
Cracked it. Comments work, just to fix snippets too…

**Comment by jrodl3r** [comment]
@silvenon Nice! Can't wait to see your code :beers:

**Comment by silvenon** [comment]
It turns out snippets aren't as easy-peasy, so it might take me a while.

**Comment by sergeche** [comment]
Should be fixed in v2.3.4

**Comment by silvenon** [comment]
Yep, thanks a lot!

**Comment by bennypowers** [comment]
I have this behaviour still, 1.5 years later.

**Comment by LeaVerou** [comment]
Just came here to report it and found this when searching for previous bug reports.
Is anyone working on this? Still happens in 2.4.3

**Comment by sergeche** [comment]
You can try a new plugin: https://github.com/emmetio/atom-plugin
